---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hello-jenkins"
  namespace: "default"
  labels:
    app: "hello-jenkins"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hello-jenkins"
  template:
    metadata:
      labels:
        app: "hello-jenkins"
    spec:
      containers:
      - name: "hello-jenkins"
        image: "bryantplaudo/hello:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: ilb-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: hello-jenkins
spec:
  type: LoadBalancer
  selector:
    app: hello-jenkins
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP